### ISSUE TITLE
Using snapcrawl via proxy?

### ISSUE THREAD

**Issue by pourkinl** [DannyBen/snapcrawl#10]
Not an issue but a question:
Can I use snapcrawl via a proxy, if so how?
Ideally I would like to try via a local TOR proxy
Thanks

**Comment by DannyBen** [comment]
Well, I am not sure, not using TOR. What I can tell you is this:

1. It does not have any proxy settings
2. If you can create a tunnel (so that the target site is accessible through some other address) then probably yes.

**Comment by pourkinl** [comment]
Thanks. 
I got this to work with a simple iptables configuration to force all traffic to my proxy.
All working nicely and thanks for the work.

**Comment by DannyBen** [comment]
Cool. Enjoy.
