### ISSUE TITLE
Save all versions of snapshot?

### ISSUE THREAD

**Issue by pourkinl** [DannyBen/snapcrawl#11]
While the time feature allows a new fresh snapshot to be taken, could I prevent the overwriting of the previous snapshot with the same filename?
I am doing comparisons between snapshots so would like to keep previous copies as well.
I could copy and rename in between snapcrawl but would prefer the option of a timestamp or version?
Thanks

**Comment by DannyBen** [comment]
Why not use the `--folder FOLDER` option to save each run in its own folder?

Something like this would save in a folder like `2019-06-13`:

```
snapcrawl go example.com --folder `date +%Y-%m-%d`
```

(although I see that the --folder option is not working properly, I can fix it quickly)

**Comment by pourkinl** [comment]
Yes I can do that.
Would have preferred to prefix filename or similar but its your work load not mine :-)
Cheers

**Comment by DannyBen** [comment]
Yeah, well - you want prefix, someone else will want suffix - so the only way to really support various use cases is to provide something like `--filename "anything-%{url}-anything-else"`.

Probably not too difficult to implement.

For the time being, I will deploy a fix for the folder bug and see about adding this later.

**Comment by DannyBen** [comment]
- Released version 0.2.7 to rubygems with the `--folder` fix
- If you are using the docker image, it was also pushed to dockerhub and being built now

**Comment by DannyBen** [comment]
Will this help?

```
 -n --name TEMPLATE
    Filename template. Use '%{url}' anywhere in the name to use the captured
    URL in the filename [default: %{url}]
```

```
$ snapcrawl go example.com --name "screenshot-%{url}"
$ snapcrawl go example.com --name "`date +%Y%m%d`_%{url}"
```

**Comment by pourkinl** [comment]
That is *exactly* what I wanted. Thanks so much.
```
-rw-r--r--  1 bob bob 1594555 Jun 14 10:06 20190614100623_http-x.png
-rw-r--r--  1 bob bob 1384403 Jun 14 10:06 20190614100600_http-x.png
```

**Comment by DannyBen** [comment]
Cool. Happy snapshotting.
