### ISSUE TITLE
error : Cliver::Dependency::VersionMismatch

### ISSUE THREAD

**Issue by szydloit** [DannyBen/snapcrawl#18]
Story:

1. Deleted 0.2.8 image container
docker rmi 584bf803d1ce
2. Pulled 0.3.0
docker pull dannyben/snapcrawl
3.  docker-compose run snapcrawl go https://the.com -d 2
![image](https://user-images.githubusercontent.com/54842471/64634917-a848ad80-d3fe-11e9-8716-1b893364b855.png)
4. Reproduced steps 1-3 thought it was git download error but no result

Error
Could not find an executable 'phantomjs' that matched the requirements '>= 1.8.1', '< 3.0'. Found versions were {"/usr/local/bin/phantomjs"=>"139649747263104"}.

Thank you for your work!

**Comment by DannyBen** [comment]
Dependency hell... this is only a problem with the docker - phantomjs version issues again. I will investigate...

**Comment by DannyBen** [comment]
Found it. I actually fixed this very same problem somewhere else.

For now, you can try running with this command:

```
$ docker run --rm -it -e OPENSSL_CONF=/etc/ssl/ dannyben/snapcrawl:0.3.0 go example.com
```

The key here is the `OPENSSL_CONF` environment variable.
I will release a new docker image with this baked in.

**Comment by DannyBen** [comment]
New docker image was published.

**Comment by szydloit** [comment]
> Found it. I actually fixed this very same problem somewhere else.
> 
> For now, you can try running with this command:
> 
> ```
> $ docker run --rm -it -e OPENSSL_CONF=/etc/ssl/ dannyben/snapcrawl:0.3.0 go example.com
> ```
> 
> The key here is the `OPENSSL_CONF` environment variable.
> I will release a new docker image with this baked in.
Thank you,
while running like this i had to define folder, where snaps should be saved. This works:

docker run --rm -it -e OPENSSL_CONF=/etc/ssl/ -v "/c/docker/snap:/app"  dannyben/snapcrawl:0.3.0  go https://example.org -d 10
