### ISSUE TITLE
Add the ability to pass headers into the application

### ISSUE THREAD

**Issue by corymcdonald** [DannyBen/snapcrawl#3]
It would be super cool if we could pass in headers into the application. I have an authentication system that I would like to be able to leverage and without cookies/headers I am unable to crawl my website.

**Comment by DannyBen** [comment]
snapcrawl uses the [screencap](https://github.com/maxwell/screencap) gem for taking the snapshots, and I am not sure it supports it. I will take a look later and if it does, it should be easy to add.
