### ISSUE TITLE
Is it possible to specify an amount of time to wait for the page to load?

### ISSUE THREAD

**Issue by gregbrant2** [DannyBen/snapcrawl#35]
Is it possible to specify a timeout to wait before snapping the page? Currently I'm getting half-rendered pages due to the lazy nature of loading a modern web page with animations and whatnot.

**Comment by DannyBen** [comment]
It waits for DOM ready and currently there is no way to configure delay before taking a screenshot.
Can you give me an example single page that suffers from this problem?

Ideally - I would want to have snapcrawl wait for the page to be ready automatically, but if the page has arbitrary animations, then perhaps a configurable delay time can be added to the config.

**Comment by DannyBen** [comment]
This should be implemented at the call to webshot:

As described [here](https://github.com/vitalie/webshot#usage)

And here is a URL to test with: https://graphicmama.com/custom-character/

**Comment by DannyBen** [comment]
Released gem version 0.5.3 with this option, thanks for the suggestion.
Docker image will be ready shortly.
