### ISSUE TITLE
ignore https certificate

### ISSUE THREAD

**Issue by Orlando80** [DannyBen/snapcrawl#36]
Hi, would it be possible to have a parameter in the configuration to ignore the https certificate?

**Comment by DannyBen** [comment]
It should be easy to add, yes.

It will involve editing this line:

https://github.com/DannyBen/snapcrawl/blob/afbb7a86c00a4e7ce18b10361748dfd4d2f6ceb7/lib/snapcrawl/page.rb#L55

with `verify: false`, as described in the [HTTParty documentation](https://github.com/jnunemaker/httparty/tree/master/docs#avoid-ssl-verification)

I can probably implement it later today, but it will help if you have a URL I can test against, to ensure we get the desired result.

**Comment by DannyBen** [comment]
I have implemented this config option, it is now available in `master` if you wan tot use it right away.

I want to try and solve #35 before wrapping a new gem. If you are in a hurry, let me know and I will release a version without waiting.

**Comment by DannyBen** [comment]
Released gem version 0.5.3 with this option, thanks for the suggestion.
Docker image will be ready shortly.
