### ISSUE TITLE
Only Mobile?

### ISSUE THREAD

**Issue by awayshops** [DannyBen/snapcrawl#43]
I only seem to get mobile output. I guess I expected the width to determine the layout. Is this a known issue or am I misunderstanding how to use it? You can see the issue on https://rapidsyouthsoccer.org/ (depth 0 please)

**Comment by awayshops** [comment]
Weird. I attached the output from the command you suggested. Maybe there is
a 3rd party issue? What version of magick do you use?

*Retail Technology is Accelerating. Chart a new course.*
[image: Company logo] <https://awayshops.com/>

AwayShops <http://awayshops.com/>
*James Whalen*
Executive Director
(508) 240-4228 <5082404228>
[image: -]

**Comment by DannyBen** [comment]
Version: ImageMagick 7.1.0-8 Q16-HDRI x86_64 2021-09-12 https://imagemagick.org
