### ISSUE TITLE
Snapshots missing out on logo of the page

### ISSUE THREAD

**Issue by RishikMani** [DannyBen/snapcrawl#44]
Hi Danny,

thank you for this repository. It was really helpful with this container rather than writing complete code in Python. I intended to take snapshots from the website [Porta Fenster](https://www.porta-fenster.de/home/). Unfortunately, in every snapshot the logo seems to be not fully captured. I am uploading a snapshot for your reference, if that helps. Apart from this issue the rest looks perfectly fine.

![https-www-porta-fenster-de-unternehmen-wir-suchen-mitarbeiter-](https://user-images.githubusercontent.com/27825015/144023307-3b0950c1-f841-4cb9-b2f1-4c63061bf242.png)

**Comment by DannyBen** [comment]
Hi - unfortunately, there is not much I can do about it. This is how phantomjs sees the page. Usually you can try using different `width` value in snapcrawl, or a different `screenshot_delay` (in cases where the page has animations for example) - but none of these seem to make the logo on this website render properly.

I guess it is using some CSS that is newer and not supported by the renderer.

**Comment by RishikMani** [comment]
ok... thank you..that pretty much explains it. I'll close the issue then. :)
